### ISSUE TITLE
Add support to input for external libs

### ISSUE THREAD

**Issue by natansevero** [jwilsson/react-input-time#1]
I think in a possibility of pass a react input component of another lib to this lib. 
In this way, I could pass, for example, a React-Bootstrap input text or Material-UI input text to this lib and I could enjoy the visual design of another lib with this react-input-time.

**Comment by jwilsson** [comment]
This should be possible with the `input` prop, for example using Material-UI:

```js
<TimeInput
  input={<Input fullWidth />
/>
```

**Comment by natansevero** [comment]
That's great! Thanks a lot!
